# ------------------------------------------------------
# WILDFIRE Configuration File (config.yml)
# 
# Editing the settings in this file will change the way
# WildFire works on your server. To reset this file to
# its default values, simply delete your config.yml and
# stop/restart your server.
# ------------------------------------------------------
#
# LOADED MARKER | Dummy value to check against at start-up, don't change!
loaded: true
# 
# ENABLED | If true, fire-based items may rarely trigger a flash fire. Must be enabled manually.
enabled: false
#
# BLAZE | If true, wildfires have a small chance to spawn a Blaze, as well.
blaze: false
#
# LANGUAGE | Currently supported languages: English only (for now!)
language: English
# 
# SILENT MODE | If true, most messages will not be relayed to players.
silentMode: false
# 
# PERMISSIONS REQUIREMENT | If true, players must have the proper permissions to use basic WildFire commands.
permissions: false
#
# FOR MORE INFO | Link TBA